apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdeployment
  labels:
    app: springbootdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootdeployment
  template:
    metadata:
      labels:
        app: springbootdeployment
    spec:
      containers:
        - name: springbootdeployment
          image: princesingh1996/skillupjava
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8786
          
---
apiVersion: v1
kind: Service
metadata:
  name: springbootdeployment
spec:
  ports:
    - protocol: "TCP"
      port: 8786
      targetPort: 8786
  selector:
    app: springbootdeployment
  type: NodePort

